on:
  push:
    branches: 
      - branch1 
       



jobs: 
  build:
    runs-on: ubuntu-latest


    steps: 
      - name: 'Before'
        run: ls
      - uses : actions/checkout@v3

      - name : 'Login to docker hub'
        run : docker login --username mariammousa --password dckr_pat_LgIXNaE1DOA01nKzsAyoCwo47eA 

      
      